In [23]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

data = pd.read_excel('Data/DecisionTree Exam-2.xlsx')
data.drop('ID', axis=1, inplace=True)
data.head()

,Study for exam,Pass exam,Studdent background,Working Status
0,No,Yes,CS,W
1,Yes,No,Other,W
2,Yes,No,CS,NW
3,Yes,No,CS,W
4,No,Yes,Maths,W


In [24]:
data['Pass exam'] = data['Pass exam'].map({'Yes': 1, 'No': 0})
data['Study for exam'] = data['Study for exam'].map({'Yes': 1, 'No': 0})
data['Studdent background'] = data['Studdent background'].map({'CS': 1, 'Maths': 2, 'Other': 3})
data['Working Status'] = data['Working Status'].map({'W': 1, 'NW': 0})
data

,Study for exam,Pass exam,Studdent background,Working Status
0,0,1,1,1
1,1,0,3,1
2,1,0,1,0
3,1,0,1,1
4,0,1,2,1
5,1,0,3,0
6,1,0,1,0
7,1,0,3,1
8,0,1,1,1
9,0,1,2,1


In [19]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(criterion="entropy", random_state=42)
tree.fit(data.drop('Pass exam', axis=1), data['Pass exam'])

t = tree.tree_

print(t.impurity)           # entropy at each node
print(t.children_left)      # left child index
print(t.children_right)     # right child index
print(t.n_node_samples)     # samples per node

[0.99679163 0.84535094 0.         1.         0.81127812 0.91829583
 0.         0.         0.        ]
[ 1  2 -1  4  5 -1 -1 -1 -1]
[ 8  3 -1  7  6 -1 -1 -1 -1]
[15 11  5  6  4  3  1  2  4]


In [21]:
for i in range(t.node_count):
    left = t.children_left[i]
    right = t.children_right[i]

    # node whose children are leaves
    if left != -1 and t.children_left[left] == -1 and t.children_left[right] == -1:
        # compute info gain here
        n = t.n_node_samples[i]
        n_left = t.n_node_samples[left]
        n_right = t.n_node_samples[right]

        ig = t.impurity[i] - (
            (n_left / n) * t.impurity[left] +
            (n_right / n) * t.impurity[right]
        )

        print(f"Node {i} → IG: {ig}")

Node 4 → IG: 0.12255624891826566


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

# --- Data ---
X = tf.random.normal((1000, 8))

# --- Architecture ---
model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(8,)),
    keras.layers.Dense(32, activation='tanh'),
    keras.layers.Dense(16, activation='sigmoid'),
    keras.layers.Dense(4, activation='softmax')
])

output = model(X)
print(output.shape)  # Expected: (1000, 4)

In [ ]:
data = pd.read_excel('Data/DecisionTree Exam-1-1.xlsx')
data.drop('ID', axis=1, inplace=True)
data.head()

,Study for exam,Pass exam,Studdent background,Working Status
0,No,Yes,CS,W
1,Yes,No,Other,W
2,Yes,No,CS,NW
3,Yes,No,CS,W
4,No,Yes,Maths,W


In [27]:
data['Pass exam'] = data['Pass exam'].map({'Yes': 1, 'No': 0})
data['Study for exam'] = data['Study for exam'].map({'Yes': 1, 'No': 0})
data['Studdent background'] = data['Studdent background'].map({'CS': 1, 'Maths': 2, 'Other': 3})
data['Working Status'] = data['Working Status'].map({'W': 1, 'NW': 0})
data

,Study for exam,Pass exam,Studdent background,Working Status
0,0,1,1,1
1,1,0,3,1
2,1,0,1,0
3,1,0,1,1
4,0,1,2,1
5,1,0,3,0
6,1,0,1,0
7,1,0,3,1
8,0,1,1,1
9,0,1,2,1


In [28]:
X = data.drop('Pass exam', axis=1)
y = data['Pass exam']

tree = DecisionTreeClassifier(criterion='gini', random_state=0)
tree.fit(X, y)

t = tree.tree_

for i in range(t.node_count):
    left = t.children_left[i]
    right = t.children_right[i]

    # node whose children are leaves
    if left != -1 and t.children_left[left] == -1 and t.children_left[right] == -1:
        print("Last split node:", i)

Last split node: 4


In [29]:
node = 4  # last split node

left = t.children_left[node]
right = t.children_right[node]

n = t.n_node_samples[node]
n_left = t.n_node_samples[left]
n_right = t.n_node_samples[right]

gini_parent = t.impurity[node]
gini_left = t.impurity[left]
gini_right = t.impurity[right]

gini_split = (n_left / n) * gini_left + (n_right / n) * gini_right

print("Gini after split:", gini_split)

Gini after split: 0.3333333333333333
